package com.pragra.Day8;

public class Casting {
    public static void main(String[] args) {
        int x = (int) (Math.random() * 100); // 'int' inside the 'parenthesis' ins the casting method used here.
                                            // This will trim the decimal value from the double value generated by math.random() method.
                                           //  Math.random() will generated a random number btw 0.0 - 1.0


        System.out.println(x);
    }
}
